### PR TITLE
Find rules rather than use a hard-coded list

### PR DESCRIPTION
**Pull request by oalders**
This reworks some commented code. It does a few things:

1) It only loads required rules, which could make it slightly faster
2) It allows for other modules in the App::PerlNitpick::Rule namespace
   to be uploaded by other authors

### CODE REVIEW

**Comment by oalders** [comment]
Not sure if you'll be happy with this approach or with allowing 3rd party rules in the same namespace. The motivation is that I have a custom rule I've been working on and I'd like to include it in this year's Perl Advent calendar. It would be simpler to demonstrate how to use the rule if it didn't rely on a fork or pre-loading a rule via `PERL5OPT`.

**Comment by oalders** [comment]
@gugod it was great meeting you in person. I was wondering if you had any thoughts on this or if you prefer a different approach?

**Comment by gugod** [comment]
I prefer having a config file or CLI options to dictate the list of rules / plugins to be loaded. I dislike how perlcritic implicitly load the set of plugins only because there are installed... this makes it inconvenient to work on multiple projects, each with different set of rules.

**Comment by oalders** [comment]
Right. So my initial problem was that if I created a new rule, it wouldn't run because it wasn't in the hard-coded list of rules that get used. Just providing them on the command line would work with an `eval require` (or some module loader), but that would break the "list rules" functionality.

What's your preference on how to handle rules that don't live inside of this module?

**Comment by gugod** [comment]
I think we definitely want to introduce some form of plugin framework... I'm OK with what's in this PR for now. Long-term speaking, the following convention makes sense to me:

- names without `::` in them refer to the ones under `App::PerlNitPick::Rule::` namespace
- Names with `::` in them are assumed to be fully-qualified.

However, for `list` command, I don't think it'll be feasible to scan all namesaces... I'd like to constraint that part to be just scanning the `App::PerlNitPick::Rule::` namespace.

**Comment by gugod** [comment]
I'll add some changes in `rewrite` part to handle error cases... but this PR looks OK to me for now.

**Comment by oalders** [comment]
Thanks! I think this is "good enough" for my current purposes. To be fair, it was never a great solution, but at least I can move ahead with my plugin.

**Pull request merged**
